@startuml
entity User {
  *id : number
  --
  *email: string
  *password: string
  *roles: array<string>
  *created_at: Date
}

entity "Category" as c01 {
  *id: number
  --
  name: string
  logo: string
}

entity "SubCategory" as sc02 {
  *id:number
  --
  *name: string
  logo: string
  *parent_category: array<int>
}

entity "Tools" as t03 {
  *id: number
  --
  *name: string
  *logo: string  
  *parent_subcategory: array<int>
  *affiliate_ref: string
  *short_description: string
  *description: string
  *features: string
  *code_promo: string
}

c01 |o..o{  sc02
sc02 |o..o{  t03
@enduml