@startuml
entity User {
  *id : number
  --
  *email: string
  *password: string
  *roles: array<string>
  *created_at: Date
}

entity "Category" as c01 {
  *id: number
  --
  *name: string
  *url: string
  logo: string
}

entity "SubCategory" as sc02 {
  *id:number
  --
  *name: string
  *url: string
  *categories: array<int>
  logo: string
}

entity "Tools" as t03 {
  *id: number
  --
  *name: string
  *url: string
  *sub_categories: array<int>
  *short_description: string
  *description: text
  *affiliate_ref: string
  *code_promo: string
  logo: string
}

c01 |o..o{  sc02
sc02 |o..o{  t03
@enduml