version: "3.8"

services:
  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: digiwiki
    ports:
      - 15432:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=sigl@eseo.fr
      - PGADMIN_DEFAULT_PASSWORD=password
    ports:
      - "5050:80"

  php-fpm:
    container_name: php-fpm
    build:
      context: ./apps/php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./apps/back-symfony/:/var/www
      - /var/www/var
      - /var/www/vendor
      - ./apps/php-fpm/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  nginx:
    container_name: nginx
    build:
      context: ./apps/nginx
    volumes:
      - ./apps/back-symfony/:/var/www
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./apps/nginx/sites/:/etc/nginx/sites-available
      - ./apps/nginx/conf.d/:/etc/nginx/conf.d
      - ./apps/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
      - "443:443"

  front-react:
    container_name: front-react
    build:
      context: ./apps/front-react
      dockerfile: Dockerfile
    volumes:
      - ./apps/front-react/:/app
      - /app/node_modules
    ports:
      - "9090:9090"
    environment:
      - CHOKIDAR_USEPOLLING=true
